# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

################################################################################
##
## EFIT - Fitness manager
## Main Window, comes from login.py
## By ErtonDev
##
################################################################################

## MODULES
################################################################################
import io
import random
import subprocess
from PySide2 import QtCore, QtGui, QtWidgets
from pathlib import Path

## SETUP
################################################################################
client_path = Path(__file__)

## GLOBALS
################################################################################
frasesMotivadoras = ["Adiós excusas, hola resultados.",
                     "No te puedes poner límites, nada es imposible.",
                     "¡Levántate y entrena! Pero no olvides descansar...",
                     "¡Cambia el no puedo por un si quiero!",
                     "Los ganadores nunca se rinden, los que se rinden no ganan.",
                     "El deporte no construye el carácter, lo revela.",
                     "No todos los días serán buenos, pero nunca te rindas.",
                     "La diferencia entre lo posible e imposible la determina uno mismo.",
                     "No te compares con el resto, compárate con la persona que eras ayer.",
                     "Las cosas no cambian por si solas. Debes hacer que cambien.",
                     "Establece metas y no te detengas hasta que las cumplas.",
                     "¿Qué hubiera pasado si no lo hubiese intentado?",
                     "Hidrátate y alimentate adecuadamente.",
                     "¡Disfruta del entrenamiento y la competición!",
                     "Un calentamiento previo es esencial. ¡No lo olvides!",
                     "Estira tus músculos al empezar y acabar un entreno.",
                     "Si te lesionas... ¡No sigas! Recupérate y sigue después.",
                     "El éxito no es un accidente.",
                     "Cuando quieres algo con intensidad ningún sacrificio es demasiado grande."]

## CLIENT
################################################################################
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon(str((client_path / "../images/logo_efit.png").resolve())))
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frase = QtWidgets.QLabel(self.centralwidget)
        self.frase.setGeometry(QtCore.QRect(20, 20, 871, 31))
        font = QtGui.QFont()
        font.setFamily("Gayathri Thin")
        font.setPointSize(20)
        font.setItalic(True)
        self.frase.setFont(font)
        self.frase.setAlignment(QtCore.Qt.AlignCenter)
        self.frase.setObjectName("frase")
        self.frame_a = QtWidgets.QFrame(self.centralwidget)
        self.frame_a.setGeometry(QtCore.QRect(20, 10, 861, 151))
        self.frame_a.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 15px;")
        self.frame_a.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_a.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_a.setObjectName("frame_a")
        self.label1 = QtWidgets.QLabel(self.frame_a)
        self.label1.setGeometry(QtCore.QRect(0, 120, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label1.setFont(font)
        self.label1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.frame_a)
        self.label2.setGeometry(QtCore.QRect(280, 120, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label2.setFont(font)
        self.label2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.frame_a)
        self.label3.setGeometry(QtCore.QRect(590, 120, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label3.setFont(font)
        self.label3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.countTime = QtWidgets.QLabel(self.frame_a)
        self.countTime.setGeometry(QtCore.QRect(50, 50, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.countTime.setFont(font)
        self.countTime.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));")
        self.countTime.setAlignment(QtCore.Qt.AlignCenter)
        self.countTime.setObjectName("countTime")
        self.countSince = QtWidgets.QLabel(self.frame_a)
        self.countSince.setGeometry(QtCore.QRect(350, 50, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.countSince.setFont(font)
        self.countSince.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));")
        self.countSince.setAlignment(QtCore.Qt.AlignCenter)
        self.countSince.setObjectName("countSince")
        self.countCant = QtWidgets.QLabel(self.frame_a)
        self.countCant.setGeometry(QtCore.QRect(640, 50, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.countCant.setFont(font)
        self.countCant.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));")
        self.countCant.setAlignment(QtCore.Qt.AlignCenter)
        self.countCant.setObjectName("countCant")
        self.indicator1 = QtWidgets.QPushButton(self.frame_a)
        self.indicator1.setGeometry(QtCore.QRect(230, 70, 21, 21))
        self.indicator1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(85, 87, 83, 0.4);\n"
"    border-style: solid;\n"
"    border-color: rgb(136, 138, 133);\n"  
"    border-radius: 10px;\n"
"    border-width: 1.5px;\n" 
"}")
        self.indicator1.setText("")
        self.indicator1.setObjectName("indicator1")
        self.indicator2 = QtWidgets.QPushButton(self.frame_a)
        self.indicator2.setGeometry(QtCore.QRect(540, 70, 21, 21))
        self.indicator2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(85, 87, 83, 0.4);\n"
"    border-style: solid;\n"
"    border-color: rgb(136, 138, 133);\n"  
"    border-radius: 10px;\n"
"    border-width: 1.5px;\n" 
"}")
        self.indicator2.setText("")
        self.indicator2.setObjectName("indicator2")
        self.indicator3 = QtWidgets.QPushButton(self.frame_a)
        self.indicator3.setGeometry(QtCore.QRect(820, 70, 21, 21))
        self.indicator3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(85, 87, 83, 0.4);\n"
"    border-style: solid;\n"
"    border-color: rgb(136, 138, 133);\n"  
"    border-radius: 10px;\n"
"    border-width: 1.5px;\n" 
"}")
        self.indicator3.setText("")
        self.indicator3.setObjectName("indicator3")
        self.frame_c = QtWidgets.QFrame(self.centralwidget)
        self.frame_c.setGeometry(QtCore.QRect(20, 510, 861, 81))
        self.frame_c.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(235, 235, 235, 255), stop:1 rgba(254, 254, 254, 255));\n"
"\n"
"border-radius: 15px;")
        self.frame_c.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_c.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_c.setObjectName("frame_c")
        self.mainBtn = QtWidgets.QPushButton(self.frame_c)
        self.mainBtn.setGeometry(QtCore.QRect(350, 20, 181, 41))
        self.mainBtn.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: rgb(78, 154, 6);\n"
"}\n"
"")
        self.mainBtn.setAutoDefault(False)
        self.mainBtn.setDefault(True)
        self.mainBtn.setObjectName("mainBtn")
        self.loadBtn = QtWidgets.QPushButton(self.frame_c)
        self.loadBtn.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.loadBtn.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: rgb(78, 154, 6);\n"
"}\n"
"")
        self.loadBtn.setAutoDefault(False)
        self.loadBtn.setDefault(False)
        self.loadBtn.setObjectName("loadBtn")
        self.info = QtWidgets.QLabel(self.frame_c)
        self.info.setGeometry(QtCore.QRect(550, 20, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.info.setFont(font)
        self.info.setStyleSheet("color: rgba(0, 0, 0, 0.5);\n"
"background-color: rgba(238, 238, 236, 0);")
        self.info.setWordWrap(True)
        self.info.setObjectName("info")
        self.reload = QtWidgets.QLabel(self.frame_c)
        self.reload.setGeometry(QtCore.QRect(70, 20, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.reload.setFont(font)
        self.reload.setStyleSheet("color: rgba(0, 0, 0, 0.5);\n"
"background-color: rgba(238, 238, 236, 0);")
        self.reload.setWordWrap(True)
        self.reload.setObjectName("reload")
        self.frame_b = QtWidgets.QFrame(self.centralwidget)
        self.frame_b.setGeometry(QtCore.QRect(20, 170, 861, 331))
        self.frame_b.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 15px;")
        self.frame_b.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_b.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_b.setObjectName("frame_b")
        self.entInfo = QtWidgets.QLabel(self.frame_b)
        self.entInfo.setGeometry(QtCore.QRect(10, 50, 421, 271))
        self.entInfo.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));\n"
"\n"
"    color: rgba(0, 0, 0, 0.4);\n"
"\n"    
"    padding-left: 10px;"                                   
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));\n"
"\n"
"    color: rgba(0, 0, 0, 0.8);\n"
"}")
        self.entInfo.setScaledContents(True)
        self.entInfo.setWordWrap(True)
        self.entInfo.setIndent(-25)
        self.entInfo.setObjectName("entInfo")
        self.entSpin = QtWidgets.QSpinBox(self.frame_b)
        self.entSpin.setGeometry(QtCore.QRect(120, 10, 311, 31))
        self.entSpin.setStyleSheet("QSpinBox {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));\n"
"}")
        self.entSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.entSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.entSpin.setObjectName("entSpin")
        self.entSpin.setMaximum(10)
        self.buscaBtn = QtWidgets.QPushButton(self.frame_b)
        self.buscaBtn.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.buscaBtn.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: rgb(78, 154, 6);\n"
"}\n"
"")
        self.buscaBtn.setAutoDefault(False)
        self.buscaBtn.setDefault(False)
        self.buscaBtn.setObjectName("buscaBtn")
        self.statsFrame = QtWidgets.QFrame(self.frame_b)
        self.statsFrame.setGeometry(QtCore.QRect(449, 49, 401, 271))
        self.statsFrame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));")
        self.statsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statsFrame.setObjectName("statsFrame")
        self.statsLabelBrazos = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelBrazos.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.statsLabelBrazos.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelBrazos.setObjectName("statsLabelBrazos")
        self.statsBtnBrazos = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnBrazos.setGeometry(QtCore.QRect(130, 10, 261, 21))
        self.statsBtnBrazos.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnBrazos.setText("")
        self.statsBtnBrazos.setObjectName("statsBtnBrazos")
        self.statsLabelEspalda = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelEspalda.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.statsLabelEspalda.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelEspalda.setObjectName("statsLabelEspalda")
        self.statsBtnEspalda = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnEspalda.setGeometry(QtCore.QRect(130, 40, 261, 21))
        self.statsBtnEspalda.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnEspalda.setText("")
        self.statsBtnEspalda.setObjectName("statsBtnEspalda")
        self.statsLabelPectoral = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelPectoral.setGeometry(QtCore.QRect(10, 70, 111, 21))
        self.statsLabelPectoral.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelPectoral.setObjectName("statsLabelPectoral")
        self.statsLabelAbdomen = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelAbdomen.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.statsLabelAbdomen.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelAbdomen.setObjectName("statsLabelAbdomen")
        self.statsLabelPiernas = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelPiernas.setGeometry(QtCore.QRect(10, 130, 111, 21))
        self.statsLabelPiernas.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelPiernas.setObjectName("statsLabelPiernas")
        self.statsLabelFlexibilidad = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelFlexibilidad.setGeometry(QtCore.QRect(10, 170, 111, 20))
        self.statsLabelFlexibilidad.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelFlexibilidad.setObjectName("statsLabelFlexibilidad")
        self.statsBtnPectoral = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnPectoral.setGeometry(QtCore.QRect(130, 70, 261, 21))
        self.statsBtnPectoral.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnPectoral.setText("")
        self.statsBtnPectoral.setObjectName("statsBtnPectoral")
        self.statsBtnAbdomen = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnAbdomen.setGeometry(QtCore.QRect(130, 100, 261, 21))
        self.statsBtnAbdomen.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnAbdomen.setText("")
        self.statsBtnAbdomen.setObjectName("statsBtnAbdomen")
        self.statsBtnPiernas = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnPiernas.setGeometry(QtCore.QRect(130, 130, 261, 21))
        self.statsBtnPiernas.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnPiernas.setText("")
        self.statsBtnPiernas.setObjectName("statsBtnPiernas")
        self.statsBtnFlexibilidad = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnFlexibilidad.setGeometry(QtCore.QRect(130, 170, 261, 20))
        self.statsBtnFlexibilidad.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnFlexibilidad.setText("")
        self.statsBtnFlexibilidad.setObjectName("statsBtnFlexibilidad")
        self.statsLabelVelocidad = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelVelocidad.setGeometry(QtCore.QRect(10, 200, 111, 21))
        self.statsLabelVelocidad.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelVelocidad.setObjectName("statsLabelVelocidad")
        self.statsLabelFuerza = QtWidgets.QLabel(self.statsFrame)
        self.statsLabelFuerza.setGeometry(QtCore.QRect(10, 230, 111, 21))
        self.statsLabelFuerza.setStyleSheet("padding-left: 10px;\n"
"border-radius: 10px;")
        self.statsLabelFuerza.setObjectName("statsLabelFuerza")
        self.statsBtnVelocidad = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnVelocidad.setGeometry(QtCore.QRect(130, 200, 261, 20))
        self.statsBtnVelocidad.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnVelocidad.setText("")
        self.statsBtnVelocidad.setObjectName("statsBtnVelocidad")
        self.statsBtnFuerza = QtWidgets.QPushButton(self.statsFrame)
        self.statsBtnFuerza.setGeometry(QtCore.QRect(130, 230, 261, 21))
        self.statsBtnFuerza.setStyleSheet("background-color: rgba(85, 87, 83, 0.4);\n"
"border-style: solid;\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 10px;\n"
"border-width: 1.5px;")
        self.statsBtnFuerza.setText("")
        self.statsBtnFuerza.setObjectName("statsBtnFuerza")
        self.divisorLine = QtWidgets.QFrame(self.statsFrame)
        self.divisorLine.setGeometry(QtCore.QRect(10, 160, 381, 1))
        self.divisorLine.setStyleSheet("background-color: rgba(136, 138, 133, 0.3);")
        self.divisorLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.divisorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divisorLine.setObjectName("divisorLine")
        self.efectsBtn = QtWidgets.QPushButton(self.frame_b)
        self.efectsBtn.setGeometry(QtCore.QRect(450, 10, 401, 31))
        self.efectsBtn.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.011, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(223, 223, 223, 255), stop:1 rgba(248, 248, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: rgb(78, 154, 6);\n"
"}\n"
"")
        self.efectsBtn.setAutoDefault(False)
        self.efectsBtn.setDefault(False)
        self.efectsBtn.setObjectName("efectsBtn")
        self.frame_a.raise_()
        self.frase.raise_()
        self.frame_c.raise_()
        self.frame_b.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionA_adir = QtWidgets.QAction(MainWindow)
        self.actionA_adir.setObjectName("actionA_adir")
        self.actionEditar = QtWidgets.QAction(MainWindow)
        self.actionEditar.setObjectName("actionEditar")
        self.actionEliminar = QtWidgets.QAction(MainWindow)
        self.actionEliminar.setObjectName("actionEliminar")
        self.actionPerfil = QtWidgets.QAction(MainWindow)
        self.actionPerfil.setObjectName("actionPerfil")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionA_adir_ejercicios = QtWidgets.QAction(MainWindow)
        self.actionA_adir_ejercicios.setObjectName("actionA_adir_ejercicios")
        self.actionEditar_ejercicios = QtWidgets.QAction(MainWindow)
        self.actionEditar_ejercicios.setObjectName("actionEditar_ejercicios")
        self.actionEmpezar_un_entrenamiento = QtWidgets.QAction(MainWindow)
        self.actionEmpezar_un_entrenamiento.setObjectName("actionEmpezar_un_entrenamiento")
        self.actionAcabar_un_entrenamiento = QtWidgets.QAction(MainWindow)
        self.actionAcabar_un_entrenamiento.setObjectName("actionAcabar_un_entrenamiento")
        self.actionAcceder_a_tus_datos = QtWidgets.QAction(MainWindow)
        self.actionAcceder_a_tus_datos.setObjectName("actionAcceder_a_tus_datos")

        self.retranslateUi(MainWindow)
        self.setupMainWindow()

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mainBtn, self.loadBtn)
        MainWindow.setTabOrder(self.loadBtn, self.buscaBtn)
        MainWindow.setTabOrder(self.buscaBtn, self.entSpin)
        MainWindow.setTabOrder(self.entSpin, self.efectsBtn)

        ## BACKEND
        ################################################################################
        self.mainBtn.clicked.connect(self.openTrainWindow)
        self.loadBtn.clicked.connect(self.refreshMainWindow)
        self.buscaBtn.clicked.connect(lambda: self.showTrainPreview(int(self.entSpin.value())))

    def setupMainWindow(self):
        pass

    def refreshMainWindow(self):
        pass

    def openTrainWindow(self):
        subprocess.Popen(['python3', (client_path / '../train.py').resolve()])  # Opens train window

    def showTrainPreview(self, number = 0):
        if number == 0:
            pass

        else:
            pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EFit"))
        self.frase.setText(_translate("MainWindow", random.choice(frasesMotivadoras)))
        self.label1.setText(_translate("MainWindow", "Tiempo medio de entrenamiento"))
        self.label2.setText(_translate("MainWindow", "Tiempo medio entre entrenamientos"))
        self.label3.setText(_translate("MainWindow", "Cantidad media de ejercicios"))
        self.countTime.setText(_translate("MainWindow", "00:00"))
        self.countSince.setText(_translate("MainWindow", "0 días"))
        self.countCant.setText(_translate("MainWindow", "0"))
        self.mainBtn.setText(_translate("MainWindow", "Nuevo entrenamiento"))
        self.loadBtn.setText(_translate("MainWindow", "R"))
        self.info.setText(_translate("MainWindow", "Registra nuevos entrenamientos para acceder a información detallada sobre tus rutinas de ejercicio."))
        self.reload.setText(_translate("MainWindow", "Este botón actualiza tus estadísticas. Pulsarlo mostrará los valores actuales."))
        self.entInfo.setText(_translate("MainWindow", "Selecciona un entrenamiento registrado para mostrar sus detalles en el menú superior."))
        self.buscaBtn.setText(_translate("MainWindow", "Busca"))
        self.statsLabelBrazos.setText(_translate("MainWindow", "Brazos"))
        self.statsLabelEspalda.setText(_translate("MainWindow", "Espalda"))
        self.statsLabelPectoral.setText(_translate("MainWindow", "Pectoral"))
        self.statsLabelAbdomen.setText(_translate("MainWindow", "Abdomen"))
        self.statsLabelPiernas.setText(_translate("MainWindow", "Piernas"))
        self.statsLabelFlexibilidad.setText(_translate("MainWindow", "Flexibilidad"))
        self.statsLabelVelocidad.setText(_translate("MainWindow", "Velocidad"))
        self.statsLabelFuerza.setText(_translate("MainWindow", "Fuerza"))
        self.efectsBtn.setText(_translate("MainWindow", "Efectos de tu entrenamiento"))
        self.actionA_adir.setText(_translate("MainWindow", "Añadir"))
        self.actionA_adir.setStatusTip(_translate("MainWindow", "Crea un nuevo ejercicio personalizado."))
        self.actionA_adir.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionEditar.setText(_translate("MainWindow", "Editar"))
        self.actionEditar.setStatusTip(_translate("MainWindow", "Edita un ejercicio."))
        self.actionEditar.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.actionEliminar.setStatusTip(_translate("MainWindow", "Elimina un ejercicio."))
        self.actionEliminar.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPerfil.setText(_translate("MainWindow", "Perfil"))
        self.actionPerfil.setStatusTip(_translate("MainWindow", "Muestra tu información personal"))
        self.actionPerfil.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setStatusTip(_translate("MainWindow", "Vuelve a la pestaña de inicio."))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionA_adir_ejercicios.setText(_translate("MainWindow", "Añadir ejercicios"))
        self.actionEditar_ejercicios.setText(_translate("MainWindow", "Editar ejercicios"))
        self.actionEmpezar_un_entrenamiento.setText(_translate("MainWindow", "Empezar un entrenamiento"))
        self.actionAcabar_un_entrenamiento.setText(_translate("MainWindow", "Acabar un entrenamiento"))
        self.actionAcceder_a_tus_datos.setText(_translate("MainWindow", "Acceder a tus datos"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
